### ISSUE TITLE
accuracy of training_caption with freezing detector

### ISSUE THREAD

**Issue by verigle** [davidnvq/grit#18]
with suggestion of `accumulation_steps` in #15 , I modified the code of caption_engine.py of train_xe function 

```
    with tqdm(desc=f'Epoch {epoch} - train', unit='it', total=len(dataloaders['train'])) as pbar:
        for it, batch in enumerate(dataloaders['train']):
            out = model(batch['samples'], batch['captions'])

            captions_gt = batch['captions'][:, 1:].contiguous()
            out = out[:, :-1].contiguous()
            loss = loss_fn(out.view(-1, len(text_field.vocab)), captions_gt.view(-1))
            loss = loss / config.optimizer.accumulation_steps
            loss.backward()

            loss = gather_result(loss)
            running_loss += loss.item()

            pbar.set_postfix(loss=running_loss / (it + 1))
            pbar.update()

            if scheduler is not None:
                # accumate
                if (it + 1) % config.optimizer.accumulation_steps == 0:
                    optimizers['model'].step()
                    optimizers['backbone'].step()

                    lr = scheduler.step()
                    assert optimizers['model'].param_groups[0]['lr'] == lr, "LR scheduler doesn't work properly."

                    optimizers['model'].zero_grad()
                    optimizers['backbone'].zero_grad()


```

but the CIDEr  score of CIDEr first epoch is very low

```
Epoch 0 - train: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 4425/4425 [13:18<00:00,  5.01it/s, loss=1.25][W CudaIPCTypes.cpp:15] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]
Epoch 0 - train: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 4425/4425 [13:21<00:00,  5.52it/s, loss=1.25]
Epoch 0 - validation:  99%|████████████████████████████████████████████████████████████████████████████████████████████████▌| 195/196 [00:25<00:00, 12.46it/s, loss=3.97][W CudaIPCTypes.cpp:15] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]
Epoch 0 - validation: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 196/196 [00:25<00:00,  7.59it/s, loss=3.97]
Epoch 0 - evaluation on valid:   0%|                                                                                                             | 0/157 [00:00<?, ?it/s]Number of iterations: 1, batch_size=32, Total time per 1 batch: 0.22200s
Epoch 0 - evaluation on valid:  64%|███████████████████████████████████████████████████████████████                                    | 100/157 [00:25<00:11,  4.81it/s]Number of iterations: 101, batch_size=32, Total time per 1 batch: 0.20595s
Epoch 0 - evaluation on valid:  99%|██████████████████████████████████████████████████████████████████████████████████████████████████▎| 156/157 [00:37<00:00,  4.76it/s][W CudaIPCTypes.cpp:15] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]
Epoch 0 - evaluation on valid: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 157/157 [00:37<00:00,  4.16it/s]
Epoch: 0 iters: 157
Total time per 1 batch: 0.20528s
Epoch 0: valid scores: {'BLEU': [0.4669783296661464, 0.24582240555971746, 0.13479587494094583, 0.07239531663650367], 'METEOR': 0.10954924428703441, 'ROUGE': 0.34872282632850365, 'CIDEr': 0.08790172488631927}

caption_4ds_20220906, B-IM, 384_640, maxwh, True, 0, valid, 8.79, 46.70, 7.24, 34.87, 10.95, 24.58, 13.48, 1.25, 0.00, 0.00, fr_xe, 3.97
Epoch 0 - evaluation on test:   0%|                                                                                                              | 0/157 [00:00<?, ?it/s]Number of iterations: 1, batch_size=32, Total time per 1 batch: 0.21069s
Epoch 0 - evaluation on test:  64%|███████████████████████████████████████████████████████████████▋                                    | 100/157 [00:25<00:11,  4.82it/s]Number of iterations: 101, batch_size=32, Total time per 1 batch: 0.20469s
Epoch 0 - evaluation on test:  99%|███████████████████████████████████████████████████████████████████████████████████████████████████▎| 156/157 [00:37<00:00,  4.81it/s][W CudaIPCTypes.cpp:15] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]
Epoch 0 - evaluation on test: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 157/157 [00:37<00:00,  4.17it/s]
Epoch: 0 iters: 157
Total time per 1 batch: 0.20416s
Epoch 0: test scores: {'BLEU': [0.4664962002208445, 0.24325046136142325, 0.1341976162794273, 0.0742708785109443], 'METEOR': 0.10937207416996544, 'ROUGE': 0.34777669352106455, 'CIDEr': 0.08940798205091863}

caption_4ds_20220906, B-IM, 384_640, maxwh, True, 0, test , 8.94, 46.65, 7.43, 34.78, 10.94, 24.33, 13.42, 1.25, 0.00, 0.00, fr_xe, 3.97
```

 then the CIDEr score not in range of [1.05 - 1.29] ( https://github.com/davidnvq/grit/issues/17#issuecomment-1234603645_ )

**Comment by verigle** [comment]
the output config file：

```
exp:
  seed: 42
  name: caption_4ds_20220906
  rank: 0
  ngpus_per_node: 1
  world_size: 1
  checkpoint: output/checkpoints/grit/coco/caption_4ds_20220906/checkpoint_best_valid.pth
  eval: false
  resume: false
dataset:
  overfit: false
  ann_root: ${oc.env:DATA_ROOT}/annotations
  img_root: ${oc.env:DATA_ROOT}
  hdf5_path: ${oc.env:DATA_ROOT}/all_splits_4ds.h5
  vocab_path: ${oc.env:DATA_ROOT}/annotations/vocab.json
  use_gri_feat: ${model.use_gri_feat}
  use_reg_feat: ${model.use_reg_feat}
  transform_cfg:
    size:
    - 384
    - 640
    resize_name: maxwh
    randaug: true
model:
  use_gri_feat: true
  use_reg_feat: true
  grid_feat_dim: 1024
  frozen_stages: 2
  beam_size: 5
  beam_len: 20
  dropout: 0.2
  attn_dropout: 0.2
  vocab_size: 10201
  max_len: 54
  pad_idx: 1
  bos_idx: 2
  eos_idx: 3
  d_model: 512
  n_heads: 8
  grit_net:
    n_memories: 1
    n_layers: 3
  grid_stage: -1
  detector:
    checkpoint: modelzoo/detector_checkpoint_4ds.pth
    d_model: 512
    dim_feedforward: 1024
    num_heads: 8
    num_layers: 6
    num_levels: 4
    num_points: 4
    num_queries: 150
    num_classes: 1849
    dropout: 0.1
    activation: relu
    return_intermediate: true
    with_box_refine: true
    det_module:
      reduced_dim: 512
      dim_feedforward: 1024
      num_heads: 8
      num_layers: 6
      num_levels: 4
      num_points: 4
      return_intermediate: true
      num_queries: 150
      num_classes: 1849
      dropout: 0.1
      activation: relu
      with_box_refine: true
      aux_loss: true
  cap_generator:
    decoder_name: parallel
    n_layers: 3
    activation: sigmoid
optimizer:
  warmup_init_lr: 1.0e-05
  min_lr: 0.0001
  xe_lr: 0.0001
  sc_lr: 5.0e-06
  xe_backbone_lr: 1.0e-05
  sc_backbone_lr: 5.0e-06
  weight_decay: 0.01
  beta_1: 0.9
  beta_2: 0.99
  batch_size: 32
  accumulation_steps: 4
  num_workers: 2
  freezing_xe_epochs: 10
  freezing_sc_epochs: 10
  finetune_xe_epochs: 0
  finetune_sc_epochs: 0
split: test
```

**Comment by verigle** [comment]
10 epoch log;
```
exp:
  seed: 42
  name: caption_4ds_20220906
  rank: 0
  ngpus_per_node: 1
  world_size: 1
  checkpoint: output/checkpoints/grit/coco/caption_4ds_20220906/checkpoint_best_valid.pth
  eval: false
  resume: false
dataset:
  overfit: false
  ann_root: ${oc.env:DATA_ROOT}/annotations
  img_root: ${oc.env:DATA_ROOT}
  hdf5_path: ${oc.env:DATA_ROOT}/all_splits_4ds.h5
  vocab_path: ${oc.env:DATA_ROOT}/annotations/vocab.json
  use_gri_feat: ${model.use_gri_feat}
  use_reg_feat: ${model.use_reg_feat}
  transform_cfg:
    size:
    - 384
    - 640
    resize_name: maxwh
    randaug: true
model:
  use_gri_feat: true
  use_reg_feat: true
  grid_feat_dim: 1024
  frozen_stages: 2
  beam_size: 5
  beam_len: 20
  dropout: 0.2
  attn_dropout: 0.2
  vocab_size: 10201
  max_len: 54
  pad_idx: 1
  bos_idx: 2
  eos_idx: 3
  d_model: 512
  n_heads: 8
  grit_net:
    n_memories: 1
    n_layers: 3
  grid_stage: -1
  detector:
    checkpoint: modelzoo/detector_checkpoint_4ds.pth
    d_model: 512
    dim_feedforward: 1024
    num_heads: 8
    num_layers: 6
    num_levels: 4
    num_points: 4
    num_queries: 150
    num_classes: 1849
    dropout: 0.1
    activation: relu
    return_intermediate: true
    with_box_refine: true
    det_module:
      reduced_dim: 512
      dim_feedforward: 1024
      num_heads: 8
      num_layers: 6
      num_levels: 4
      num_points: 4
      return_intermediate: true
      num_queries: 150
      num_classes: 1849
      dropout: 0.1
      activation: relu
      with_box_refine: true
      aux_loss: true
  cap_generator:
    decoder_name: parallel
    n_layers: 3
    activation: sigmoid
optimizer:
  warmup_init_lr: 1.0e-05
  min_lr: 0.0001
  xe_lr: 0.0001
  sc_lr: 5.0e-06
  xe_backbone_lr: 1.0e-05
  sc_backbone_lr: 5.0e-06
  weight_decay: 0.01
  beta_1: 0.9
  beta_2: 0.99
  batch_size: 32
  accumulation_steps: 4
  num_workers: 2
  freezing_xe_epochs: 10
  freezing_sc_epochs: 10
  finetune_xe_epochs: 0
  finetune_sc_epochs: 0
split: test

```
