### ISSUE TITLE
Question about freeze training

### ISSUE THREAD

**Issue by HHHH17** [davidnvq/grit#20]
Dear Author, I have used the code you give to freeze the backbone and detector to training the model. But after 10 epoch for XE and 10 epoch for SC, the final CIDER score is 38.0. Do you have met the same problem or do you have any idea about what is the possible reason.

**Comment by davidnvq** [comment]
Sorry for the problem that you met. Can you give me more details about the configuration file, the commands, and the machine that you used? It may give me better understanding to make a guess.

I have tried reproducing on several machines (with 8 GPUs and 1 GPU). Machine with 1 GPU gave about 3 CIDEr score, which may be fixed by the accumulation trick. Machine with 8 GPUs always give the same performance with difference < 0.5 CIDEr.

I suspect that you didn't provide or load the pretrained weights successfully?

**Comment by HHHH17** [comment]
Dear Author, Thank you for your reminding. The path of detector checkpoint I gave earlier is invalid. Now I run the command:
```
python train_caption.py \
    exp.name=freeze_train \
    model.detector.checkpoint='/home/caption/Gitcloned/grit/grit-main/checkpoints/detector_checkpoint_4ds.pth' \
    optimizer.freezing_xe_epochs=10 \
    optimizer.freezing_sc_epochs=10 \
    optimizer.finetune_xe_epochs=0 \
    optimizer.finetune_sc_epochs=0
```
I can get a meaningful results, but There is still a big gap with what you gave. After 10 epoch XE training, the results are shown below:
```
Epoch 0: test scores: {'BLEU': [0.7156505933757753, 0.5519022972103664, 0.41080635113450087, 0.2981237981504795], 'METEOR': 0.23476372777686583, 'ROUGE': 0.5236501132808339, 'CIDEr': 0.8692613882015044}
Epoch 0: valid scores: {'BLEU': [0.7151434848869074, 0.5521252876191592, 0.4097232103630596, 0.2963797565591326], 'METEOR': 0.23621160210515219, 'ROUGE': 0.5260450167143135, 'CIDEr': 0.8708782497975665}
Epoch 1: test scores: {'BLEU': [0.7525714963599234, 0.5941351484337888, 0.4532006597848748, 0.3405737279612276], 'METEOR': 0.26134581946253466, 'ROUGE': 0.553413889694981, 'CIDEr': 1.0621739319598424}
Epoch 1: valid scores: {'BLEU': [0.7509988168416816, 0.5939510228928679, 0.45213306792722063, 0.33917113655202524], 'METEOR': 0.2618399941555833, 'ROUGE': 0.552840461088358, 'CIDEr': 1.050433948901599}
Epoch 2: test scores: {'BLEU': [0.7595466602061433, 0.6019688590645143, 0.46159314138856, 0.3504133059564776], 'METEOR': 0.26730557741201927, 'ROUGE': 0.5608219901961183, 'CIDEr': 1.1094836301719446}
Epoch 2: valid scores: {'BLEU': [0.7619984561224253, 0.607194644891292, 0.46716121645228587, 0.35611563850126127], 'METEOR': 0.27016735696909233, 'ROUGE': 0.5630800651820818, 'CIDEr': 1.103546103931398}
Epoch 3: valid scores: {'BLEU': [0.7720434381450293, 0.6178342258158375, 0.4783949519612809, 0.3686972295089884], 'METEOR': 0.27555252334621116, 'ROUGE': 0.5719994623676552, 'CIDEr': 1.1494267606192206}
Epoch 3: test scores: {'BLEU': [0.7694217927598448, 0.6111059112405425, 0.4701205044303501, 0.35922334961952845], 'METEOR': 0.2716119266903038, 'ROUGE': 0.5666674067854713, 'CIDEr':1.1435790171651867}
Epoch 4: test scores: {'BLEU': [0.7693916044625394, 0.6128658893551809, 0.4758168485565689, 0.3672537402972542], 'METEOR': 0.2760303269434147, 'ROUGE': 0.5683925388551221, 'CIDEr': 1.1701486479676033}
Epoch 4: valid scores: {'BLEU': [0.7704736700671413, 0.6152893376062368, 0.47792306801335416, 0.3695759861507235], 'METEOR': 0.2774134699569805, 'ROUGE': 0.5705399194230725, 'CIDEr': 1.1588734340739126}
Epoch 5: test scores: {'BLEU': [0.770552354617129, 0.6124772862896469, 0.4731913002279038, 0.36402141803319393], 'METEOR': 0.2780705075163046, 'ROUGE': 0.5704159987823794, 'CIDEr': 1.1717018626303575}
Epoch 5: valid scores: {'BLEU': [0.7744391179237676, 0.6181898707296198, 0.4801856007226499, 0.37200008521401484], 'METEOR': 0.28001750508072554, 'ROUGE': 0.5742228226570998, 'CIDEr': 1.1741454616225033}
Epoch 6: test scores: {'BLEU': [0.7768537313485956, 0.6201300604323753, 0.4817080602674321, 0.37135457219375323], 'METEOR': 0.28102313950257357, 'ROUGE': 0.5739106419398616, 'CIDEr': 1.1865810359880677}
Epoch 6: valid scores: {'BLEU': [0.7757071838872615, 0.6180640901026254, 0.47954288346438745, 0.3711593450690459], 'METEOR': 0.2819321039702166, 'ROUGE': 0.5739471526403694, 'CIDEr': 1.1776446890880807}
Epoch 7: test scores: {'BLEU': [0.7759060676674857, 0.620045073724529, 0.48256088536917047, 0.37413320967750274], 'METEOR': 0.28258066313203084, 'ROUGE': 0.5760191460133733, 'CIDEr': 1.1994051259739844}
Epoch 7: valid scores: {'BLEU': [0.7759075418412079, 0.6206009810934064, 0.483924878318699, 0.376017068375316], 'METEOR': 0.2825932454924633, 'ROUGE': 0.5759025889154147, 'CIDEr': 1.184750794128682}
Epoch 8: test scores: {'BLEU': [0.7695891885074931, 0.612866337375667, 0.4759858405624598, 0.36776703558525764], 'METEOR': 0.2795645490519798, 'ROUGE': 0.5701154551573259, 'CIDEr': 1.181300792563674}
Epoch 8: valid scores: {'BLEU': [0.7730386511190289, 0.615892739198913, 0.4789467269452141, 0.37176350488384474], 'METEOR': 0.28146216116061046, 'ROUGE': 0.5745066795960886, 'CIDEr': 1.17671044805458}
Epoch 9: test scores: {'BLEU': [0.7760053435695401, 0.6205725054268768, 0.4836410734958435, 0.3750767190373392], 'METEOR': 0.28415604477249257, 'ROUGE': 0.5766731323730659, 'CIDEr':1.2045035524186627}
Epoch 9: valid scores: {'BLEU': [0.7786346817093811, 0.6211484969263509, 0.483513104124161, 0.3754697174759194], 'METEOR': 0.2841216222796373, 'ROUGE': 0.5772250340557926, 'CIDEr': 1.1863213459152706}
``` 
I run this model on a machine with 8 2080Ti GPU and env is torch-1.12.1 with cuda 11.3, The configs are shown below:
```
exp:
  seed: 42
  name: freeze_train
  rank: 0
  ngpus_per_node: 8
  world_size: 8
  checkpoint: ''
  eval: false
  resume: false
dataset:
  overfit: false
  ann_root: ${oc.env:DATA_ROOT}/annotations
  img_root: ${oc.env:DATA_ROOT}
  hdf5_path: ${oc.env:DATA_ROOT}/all_splits.h5
  vocab_path: ${oc.env:DATA_ROOT}/annotations/vocab.json
  use_gri_feat: ${model.use_gri_feat}
  use_reg_feat: ${model.use_reg_feat}
  transform_cfg:
    size:
    - 384
    - 640
    resize_name: maxwh
    randaug: true
model:
  use_gri_feat: true
  use_reg_feat: true
  grid_feat_dim: 1024
  frozen_stages: 2
  beam_size: 5
  beam_len: 20
  dropout: 0.2
  attn_dropout: 0.2
  vocab_size: 10201
  max_len: 54
  pad_idx: 1
  bos_idx: 2
  eos_idx: 3
  d_model: 512
  n_heads: 8
  grit_net:
    n_memories: 1
    n_layers: 3
  detector:
    checkpoint: /home/caption/Gitcloned/grit/grit-main/checkpoints/detector_checkpoint_4ds.pth
    d_model: 512
    dim_feedforward: 1024
    num_heads: 8
    num_layers: 6
    num_levels: 4
    num_points: 4
    num_queries: 150
    num_classes: 1849
    dropout: 0.1
    activation: relu
    return_intermediate: true
    with_box_refine: true
  cap_generator:
    decoder_name: parallel
    n_layers: 3
    activation: sigmoid
optimizer:
  warmup_init_lr: 1.0e-05
  min_lr: 0.0001
  xe_lr: 0.0001
  sc_lr: 5.0e-06
  xe_backbone_lr: 1.0e-05
  sc_backbone_lr: 5.0e-06
  weight_decay: 0.01
  beta_1: 0.9
  beta_2: 0.99
  batch_size: 16
  num_workers: 2
  freezing_xe_epochs: 10
  freezing_sc_epochs: 10
  finetune_xe_epochs: 0
  finetune_sc_epochs: 0
```
Could you help me to find out is there any problem in my config?

**Comment by davidnvq** [comment]
It is not easy for me to know why. Even with 1 GPU I can reproduce with reasonable performance; e.g. https://github.com/davidnvq/grit/issues/15#issuecomment-1246169088.

I expected that with 8 GPUs like your the performance will be closer to the reported results. However, what you reported disputes with my expection.

Can you help me to download this pretrained object detector ([this link](https://drive.google.com/file/d/1v0-mdgJLMqOsINfqtDpRNsJpAPKFa3IS/view?usp=sharing) - I'm using) and compare the weights with your current one (/home/caption/Gitcloned/grit/grit-main/checkpoints/detector_checkpoint_4ds.pth)?

**It would be nice to compare every key and value of all the weights.** I suspect that there is a mismatch somewhere when I renamed the weights.

**Comment by HHHH17** [comment]
I have download the pretrained object detector you give (detector_checkpoint_4ds_2.pth) and conpared with the one I used now (detector_checkpoint_4ds.pth):
```
78d61bf97f354f3a6d00a45041c2a377  detector_checkpoint_4ds.pth
78d61bf97f354f3a6d00a45041c2a377  detector_checkpoint_4ds_2.pth
```
They are exactly the same, and the cider result for 10 Epoch in [#15 ](url) is 120.29, basically the same as my training result.  
The cider results given in the paper can eventually reach 139.6 for freeze training. Do you have the training log for complete 20 epoch？

**Comment by davidnvq** [comment]
The training log was provided in https://github.com/davidnvq/grit/issues/18#issuecomment-1242698032:

```
cat result.txt
Epoch 0: valid scores: {'BLEU': [0.7538250289537521, 0.596562414985615, 0.4540185893450545, 0.33969480502142646], 'METEOR': 0.26079146802120723, 'ROUGE': 0.5553119459813104, 'CIDEr': 1.0461147458266575}
Epoch 0: test scores: {'BLEU': [0.7538096834276076, 0.5958968344182032, 0.4553681588957574, 0.3426630347328637], 'METEOR': 0.2609191614973612, 'ROUGE': 0.5564575152162115, 'CIDEr': 1.0609378106382028}
Epoch 1: test scores: {'BLEU': [0.7785420525194918, 0.6227267712579907, 0.48318177558956765, 0.37110900936399915], 'METEOR': 0.2788398012006459, 'ROUGE': 0.5748468163868693, 'CIDEr': 1.1839931965034516}
Epoch 1: valid scores: {'BLEU': [0.778855323496365, 0.6251732213529925, 0.4862454816645014, 0.374640451374451], 'METEOR': 0.27977644697342474, 'ROUGE': 0.5777731655865079, 'CIDEr': 1.1764461871293133}
Epoch 2: test scores: {'BLEU': [0.7823447997166053, 0.6290398800710232, 0.4922573666405114, 0.38225896666687104], 'METEOR': 0.2852446835394714, 'ROUGE': 0.5817635371239943, 'CIDEr': 1.2261100724095657}
Epoch 2: valid scores: {'BLEU': [0.7846525925685631, 0.634155649067113, 0.49714663098357315, 0.3867603929942251], 'METEOR': 0.28548504139308056, 'ROUGE': 0.5835172379457306, 'CIDEr': 1.2196434807827121}
Epoch 3: valid scores: {'BLEU': [0.7917327942542083, 0.6424203422561312, 0.5054563752697528, 0.39523228933069654], 'METEOR': 0.2916085270448981, 'ROUGE': 0.5917410971395807, 'CIDEr': 1.2479601987952522}
Epoch 3: test scores: {'BLEU': [0.7906897739999386, 0.6369097230969365, 0.49835775716208586, 0.3880412383761517], 'METEOR': 0.2888664429923958, 'ROUGE': 0.5883285170501267, 'CIDEr': 1.2502389474614086}
Epoch 4: valid scores: {'BLEU': [0.7957569998017531, 0.6471634818163418, 0.5116644846864994, 0.4017259182875278], 'METEOR': 0.2932035123933825, 'ROUGE': 0.5939159193613331, 'CIDEr': 1.2679474067353362}
Epoch 4: test scores: {'BLEU': [0.7942980159845641, 0.6441850389898548, 0.5097528189164301, 0.4000709255882639], 'METEOR': 0.2934497645559173, 'ROUGE': 0.5920811961336366, 'CIDEr': 1.2785493054299257}
Epoch 5: valid scores: {'BLEU': [0.7970202352961274, 0.6460475096181677, 0.5092481290741753, 0.3988404132262942], 'METEOR': 0.293771562418025, 'ROUGE': 0.5944456649831105, 'CIDEr': 1.2684498594234204}
Epoch 5: test scores: {'BLEU': [0.7946479572981971, 0.6448607696501109, 0.5093860475788792, 0.3993787811324676], 'METEOR': 0.29416671763842106, 'ROUGE': 0.594694350219191, 'CIDEr': 1.279104734906149}
Epoch 6: test scores: {'BLEU': [0.7898823296042636, 0.6368843225102946, 0.5033368888704767, 0.39599037131009784], 'METEOR': 0.2957331793867509, 'ROUGE': 0.5896175922512735, 'CIDEr': 1.2786846207140317}
Epoch 6: valid scores: {'BLEU': [0.7921119265267416, 0.6394890174963228, 0.505395350735759, 0.39649127354727426], 'METEOR': 0.2951546584765399, 'ROUGE': 0.5912797830527387, 'CIDEr': 1.26094086083513}
Epoch 7: valid scores: {'BLEU': [0.7953589267075801, 0.6448840953790032, 0.5091179225233083, 0.3988465934645186], 'METEOR': 0.2944972576853284, 'ROUGE': 0.5922647371187016, 'CIDEr': 1.267485150782694}
Epoch 7: test scores: {'BLEU': [0.797923092592688, 0.6469203098860058, 0.5112677284646816, 0.40192986485317983], 'METEOR': 0.2971981305523139, 'ROUGE': 0.5959802899904283, 'CIDEr': 1.2952236361482858}
Epoch 8: valid scores: {'BLEU': [0.7981481278271069, 0.6489911081729335, 0.5137796149165833, 0.40375749598580507], 'METEOR': 0.296309514711055, 'ROUGE': 0.5939607014800888, 'CIDEr': 1.2804176361573352}
Epoch 8: test scores: {'BLEU': [0.7981913127533568, 0.647616139988432, 0.5127104752676751, 0.40299519682268475], 'METEOR': 0.2968949157793757, 'ROUGE': 0.5945100409642673, 'CIDEr': 1.2950229705521017}
Epoch 9: test scores: {'BLEU': [0.7936862177479342, 0.6431453662200723, 0.5086368535541335, 0.39977487361802977], 'METEOR': 0.29702346000971386, 'ROUGE': 0.5939995293929079, 'CIDEr': 1.2911802443483553}
Epoch 9: valid scores: {'BLEU': [0.7957532903418028, 0.6448849552573164, 0.509262538898219, 0.39983078089529245], 'METEOR': 0.29571605978619037, 'ROUGE': 0.5928173411856615, 'CIDEr': 1.2767403521851346}
Epoch 10: valid scores: {'BLEU': [0.8392216942224467, 0.6930766554577301, 0.5484057647462168, 0.4242517692623965], 'METEOR': 0.30373537113375393, 'ROUGE': 0.6095928462919656, 'CIDEr': 1.3916730354459894}
Epoch 10: test scores: {'BLEU': [0.8371512250161982, 0.6912662532549091, 0.5494338242292505, 0.42842961194165047], 'METEOR': 0.3034593171069, 'ROUGE': 0.6074838195075987, 'CIDEr': 1.3929439731290956}
Epoch 11: valid scores: {'BLEU': [0.8338745045639491, 0.6909412333836084, 0.5478022366005478, 0.4248563841323607], 'METEOR': 0.29982710000784657, 'ROUGE': 0.6090442845413084, 'CIDEr': 1.380871963690942}
Epoch 11: test scores: {'BLEU': [0.8320881645925845, 0.6897865566785281, 0.5497962995998547, 0.4296512120498058], 'METEOR': 0.3001551836167212, 'ROUGE': 0.6095729905385621, 'CIDEr': 1.395327814840547}
Epoch 12: valid scores: {'BLEU': [0.8335816089449272, 0.691955562290691, 0.5497808338419828, 0.42712092062154966], 'METEOR': 0.2995854172105309, 'ROUGE': 0.6092121180620336, 'CIDEr': 1.3841083245164836}
Epoch 12: test scores: {'BLEU': [0.8358434910271985, 0.6927899360982215, 0.5515334705278486, 0.42963927851520434], 'METEOR': 0.30060352023996734, 'ROUGE': 0.6085176857192084, 'CIDEr': 1.3970138559169973}
Epoch 13: test scores: {'BLEU': [0.8368407870282764, 0.6927053589523655, 0.5503410971040265, 0.42778248808076114], 'METEOR': 0.30329596254764474, 'ROUGE': 0.6091348965367512, 'CIDEr': 1.3911346327574417}
Epoch 13: valid scores: {'BLEU': [0.8375819786797934, 0.6928144827887621, 0.5485425470135012, 0.42494904660063526], 'METEOR': 0.3015641520541005, 'ROUGE': 0.6094370438760679, 'CIDEr': 1.3870016917338366}
Epoch 14: valid scores: {'BLEU': [0.8397301508998447, 0.6951166862174084, 0.5501077595020255, 0.425305595268546], 'METEOR': 0.301307044864702, 'ROUGE': 0.6092071185407049, 'CIDEr': 1.3888033401841}
Epoch 14: test scores: {'BLEU': [0.8387347059300678, 0.6938256746185609, 0.5502301568894592, 0.42739577539223783], 'METEOR': 0.3022847066751842, 'ROUGE': 0.6099642379639814, 'CIDEr': 1.3938938737463365}
Epoch 15: valid scores: {'BLEU': [0.8383349351062339, 0.6939514222346885, 0.5496104450256393, 0.4256538746739609], 'METEOR': 0.30113020113868766, 'ROUGE': 0.608930887381079, 'CIDEr': 1.3881121994480983}
Epoch 15: test scores: {'BLEU': [0.8377434526189247, 0.6938947082894922, 0.5520702255956362, 0.42985101765724304], 'METEOR': 0.30209385339950307, 'ROUGE': 0.6087747503180939, 'CIDEr': 1.3930224785420147}
Epoch 16: valid scores: {'BLEU': [0.8404747079306697, 0.6945144474530267, 0.5491480576845459, 0.42432169621450344], 'METEOR': 0.3011667231732114, 'ROUGE': 0.6087723165936284, 'CIDEr': 1.3913707334426995}
Epoch 16: test scores: {'BLEU': [0.8403868539331363, 0.6947791828047277, 0.5526706479845518, 0.43114776979811276], 'METEOR': 0.3035610412601643, 'ROUGE': 0.6104259661927642, 'CIDEr': 1.4017157368840588}
Epoch 17: valid scores: {'BLEU': [0.8370814506152257, 0.6941824464543063, 0.5506641646309467, 0.426903866381421], 'METEOR': 0.3009911711830235, 'ROUGE': 0.6099568995822994, 'CIDEr': 1.3880645221570864}
Epoch 17: test scores: {'BLEU': [0.8345497554622181, 0.6922240764550124, 0.5512615294054465, 0.42992375836248503], 'METEOR': 0.3029906087443316, 'ROUGE': 0.6108695148820223, 'CIDEr': 1.395373498283653}
Epoch 18: valid scores: {'BLEU': [0.8342504349698247, 0.6909111557999621, 0.5480946427393756, 0.42480807614822885], 'METEOR': 0.298903291438397, 'ROUGE': 0.6079175955401886, 'CIDEr': 1.3779367477191458}
Epoch 18: test scores: {'BLEU': [0.8322245235372027, 0.6891459224250824, 0.5479176668734069, 0.427081860511104], 'METEOR': 0.29924427125185954, 'ROUGE': 0.608153175395876, 'CIDEr': 1.3867699582117679}
Epoch 19: valid scores: {'BLEU': [0.8375084420728919, 0.6947617266115735, 0.5507303660393632, 0.42665732219177516], 'METEOR': 0.300775230770062, 'ROUGE': 0.6091563180552525, 'CIDEr': 1.3913689397315665}
Epoch 19: test scores: {'BLEU': [0.8339521842831992, 0.6910585392547325, 0.5497944114216822, 0.4271993533383748], 'METEOR': 0.30110834748349546, 'ROUGE': 0.6090249755582172, 'CIDEr': 1.3956418029412469}
```

**Comment by HHHH17** [comment]
Thank you for your patient answer, I still have 2 questions：
1. The difference of result in [15#](https://github.com/davidnvq/grit/issues/15) and[18#](https://github.com/davidnvq/grit/issues/18) mainly because of the batch size, I use the batch size of 10, so, I can get the result close to batch size 8?
2. What batch size was used in your experiments

**Comment by davidnvq** [comment]
1. #15 used 1 GPU of 24GB while #18 used 8 GPUs (each of 48GB) = 8*48 GB.
2. #18 used default config.

**Comment by HHHH17** [comment]
Dear Author, I have checked my config again. I use the same batch size as default config (16 for each GPU). But I still get 120.45 cider after 10 epoch. Is there any other reasons that affect the results？
```
exp:
  seed: 42
  name: freeze_train
  rank: 0
  ngpus_per_node: 8
  world_size: 8
  checkpoint: ''
  eval: false
  resume: false
dataset:
  overfit: false
  ann_root: ${oc.env:DATA_ROOT}/annotations
  img_root: ${oc.env:DATA_ROOT}
  hdf5_path: ${oc.env:DATA_ROOT}/all_splits.h5
  vocab_path: ${oc.env:DATA_ROOT}/annotations/vocab.json
  use_gri_feat: ${model.use_gri_feat}
  use_reg_feat: ${model.use_reg_feat}
  transform_cfg:
    size:
    - 384
    - 640
    resize_name: maxwh
    randaug: true
model:
  use_gri_feat: true
  use_reg_feat: true
  grid_feat_dim: 1024
  frozen_stages: 2
  beam_size: 5
  beam_len: 20
  dropout: 0.2
  attn_dropout: 0.2
  vocab_size: 10201
  max_len: 54
  pad_idx: 1
  bos_idx: 2
  eos_idx: 3
  d_model: 512
  n_heads: 8
  grit_net:
    n_memories: 1
    n_layers: 3
  detector:
    checkpoint: /home/caption/Gitcloned/grit/grit-main/checkpoints/detector_checkpoint_4ds.pth
    d_model: 512
    dim_feedforward: 1024
    num_heads: 8
    num_layers: 6
    num_levels: 4
    num_points: 4
    num_queries: 150
    num_classes: 1849
    dropout: 0.1
    activation: relu
    return_intermediate: true
    with_box_refine: true
  cap_generator:
    decoder_name: parallel
    n_layers: 3
    activation: sigmoid
optimizer:
  warmup_init_lr: 1.0e-05
  min_lr: 0.0001
  xe_lr: 0.0001
  sc_lr: 5.0e-06
  xe_backbone_lr: 1.0e-05
  sc_backbone_lr: 5.0e-06
  weight_decay: 0.01
  beta_1: 0.9
  beta_2: 0.99
  batch_size: 16
  num_workers: 2
  freezing_xe_epochs: 10
  freezing_sc_epochs: 10
  finetune_xe_epochs: 0
  finetune_sc_epochs: 0
```
