### ISSUE TITLE
what is the function of the config when dataset.overfit = True

### ISSUE THREAD

**Issue by verigle** [davidnvq/grit#5]
in configs/caption/coco_config.yaml  : 
```
dataset:
  overfit: True
  ann_root: '${oc.env:DATA_ROOT}/annotations'
  img_root: '${oc.env:DATA_ROOT}'
  hdf5_path: '${oc.env:DATA_ROOT}/all_splits.h5' # this is used for freezed extractor; fast to train.
  vocab_path: '${oc.env:DATA_ROOT}/annotations/vocab.json'
  use_gri_feat: ${model.use_gri_feat}
  use_reg_feat: ${model.use_reg_feat}
```

what is the function of params of  dataset.overfit = True

in annother file : 
```
class CPairedDataset:

    def __init__(self, examples, image_field, overfit=False):
        self.examples = examples
        self.image_field = image_field
        self.overfit = overfit

    def __getitem__(self, idx):
        example = self.examples[idx]
        img_path, caption = example.image, example.tokens
        image_id = example.image_id
        img = self.image_field.preprocess(img_path)
        return img, caption, image_id

    def __len__(self):
        if self.overfit:
            return OVERFIT_SIZE
        return len(self.examples)
```

when overfit is True, why return lenght of CPaireDataset = 64?
